spring:
  application:
    name: bookstore
  datasource:
    username: root
    password: 16102004@
    url: jdbc:mysql://localhost:3306/bookstore
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate: 
        ddl-auto: update
    show-sql: true
